<a href="https://colab.research.google.com/github/bsmlhh/visionn/blob/main/lab_task_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from PIL import Image
import numpy as np

In [ ]:
# Load the image
image = Image.open('TEST.jpg').convert('L')

In [ ]:
# Convert the image to a NumPy array
image_array = np.array(image)

In [ ]:
filter = np.array([[1, 1], [1, 1]])

In [ ]:
# Apply the filter to the image
Conv = np.zeros_like(image_array)
for i in range(1, image_array.shape[0]-1):
    for j in range(1, image_array.shape[1]-1):
        Conv[i,j] = np.sum(image_array[i-1:i+1, j-1:j+1] * filter)


print(Conv)

[[  0   0   0 ...   0   0   0]
 [  0  56  50 ... 140 144   0]
 [  0  61  44 ... 140 144   0]
 ...
 [  0   6 254 ...  21  27   0]
 [  0   0 249 ...  21  26   0]
 [  0   0   0 ...   0   0   0]]
